version: "3.8"

services:

  honeypot:
    build: ./backend

    container_name: honeypot-backend

    ports:
      - "5000:5000"

    volumes:
      - ./logs:/app/logs

    restart: always

  dashboard:
    build: ./dashboard

    container_name: honeypot-dashboard

    ports:
      - "5050:5000"

    volumes:
      - ./logs:/app/logs

    restart: always

    depends_on:
      - honeypot
